force-app/main/default/objects/Global_Correlation_Id__c/Global_Correlation_Id__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Global Correlation Id</label>
</CustomObject>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Original_Log__c.field-meta.xml
<CustomField>
    <fullName>Original_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Log</label>
    <referenceTo>Log__c</referenceTo>
    <relationshipLabel>Reprocessed</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/recordTypes/Integration.recordType-meta.xml
<RecordType>
    <fullName>Integration</fullName>
    <active>true</active>
    <label>Integration</label>
</RecordType>

force-app/main/default/classes/IntegrationFrameworkUtils_Test.cls
@isTest
private class IntegrationFrameworkUtils_Test{
    @testSetup
    static void setupTestData(){
        test.startTest();
        Log__c log_Obj = new Log__c();
        log_Obj.User__c = UserInfo.getUserId();
        log_Obj.Type__c = 'Integration';
        log_Obj.Class_Name__c = 'TestClass';
        log_Obj.Method_Name__c = 'testMethod';
        Insert log_Obj;

        Global_Correlation_Id__c setting = new Global_Correlation_Id__c();
        setting.Name = IntegrationFrameworkUtils.GLOBAL_CORRELATION_SETTING_NAME;
        insert setting;

        test.stopTest();
    }
    static testMethod void test_increaseAndGetCorrelationId_UseCase1(){
        Integer correlationId = IntegrationFrameworkUtils.increaseAndGetCorrelationId();
        System.assertEquals(correlationId, 1);
    }
    static testMethod void test_increaseGetAndUpdateCorrelationId_UseCase1(){
        Integer correlationId = IntegrationFrameworkUtils.increaseAndGetCorrelationId();
        System.assertEquals(correlationId, 1);
    }
    static testMethod void test_reprocess_UseCase1(){
        List<Log__c> logList  =  [SELECT Id,User__c,Original_Log__c,Type__c from Log__c];
        String origLogId = logList.get(0).Id;
        IntegrationFrameworkUtils.reprocess(new Set<String>{origLogId});
        List<Log__c> logList1  =  [SELECT Id,User__c,Original_Log__c,Type__c,Class_Name__c,Method_Name__c from Log__c where Id <> :origLogId];
        System.assertEquals(origLogId, logList1.get(0).Original_Log__c);
        System.assertEquals('Integration', logList1.get(0).Type__c);
        System.assertEquals('TestClass', logList1.get(0).Class_Name__c);
        System.assertEquals('testMethod', logList1.get(0).Method_Name__c);
    }
}